preload = /home/bruce/Pictures/Wallpapers/2923749-868905033.jpg
preload = /home/bruce/Pictures/Wallpapers/4552407-artwork-painting-digital-art-asian-architecture-house-tower-nature-landscape-river-bridge-waterfall-trees-forest-valley-mountains-fall-leaves-252904059.jpg
preload = /home/bruce/Pictures/Wallpapers/6996b272cebdc883e4946aab3c30db32cc74cbf4_high-3441681212.webp
preload = /home/bruce/Pictures/Wallpapers/fantasy-concept-showing-longji-rice-terrace-china-stunningly-beautiful-terraced-rice-fields_743201-1428-3062637707.jpg
preload = /home/bruce/Pictures/Wallpapers/landscape-painting-traditional-chinese-style-ink-washes-depicting-mountains-river-painting-captures-essence-genre-evoking-sense-tranquility-generative-ai_213438-8856-1743990111.jpg
preload = /home/bruce/Pictures/Wallpapers/rice_field_landscape_by_epicsteps_dg01r9g-pre-2199863378.jpg
preload = /home/bruce/Pictures/Wallpapers/landscape-painting-traditional-chinese-style-ink-washes-depicting-mountains-river-painting-captures-essence-genre-evoking-sense-tranquility-generative-ai_213438-8857-21902782.jpg
preload = /home/bruce/Pictures/Wallpapers/traditional-chinese-ink-landscape-painting-silk-mountains-rivers_167857-53189-2033578658.jpg
preload = /home/bruce/Pictures/Wallpapers/wp6413890-2655930904.jpg

wallpaper = eDP-1,/home/bruce/Pictures/Wallpapers/rice_field_landscape_by_epicsteps_dg01r9g-pre-2199863378.jpg
