source = $HOME/.config/hypr/ricepaper.conf

$accent = $sage
$font = JetBrainsMono Nerd Font

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/Pictures/Wallpapers/rice_field_landscape_by_epicsteps_dg01r9g-pre-2199863378.jpg

# privacy blur
  blur_passes = 4 
  blur_size = 8

# ricepaper overlay
  color = $paper
}

# LAYOUT
label {
  monitor =
  text = Layout: $LAYOUT
  color = $mist
  font_size = 25
  font_family = $font
  position = -30, -30
  halign = right
  valign = top
}

# TIME
label {
  monitor =
  text = $TIME
  color = $mist
  font_size = 90
  font_family = $font
  position = 30, 0
  halign = left
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $mist
  font_size = 25
  font_family = $font
  position = 30, -150
  halign = left
  valign = top
}

# FINGERPRINT
{
  monitor = "";
  text = "$FPRINTPROMPT";
  color = "$ink";
  font_size = 14;
  font_family = $font;
  position = "0, -107";
  halign = "center";
  valign = "center";
}

# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $paperSoft
  font_color = $ink
  fade_on_empty = false
  placeholder_text = 󰌾 Logged in as $USER
  hide_input = false
  check_color = $accent
  fail_color = $rose
  fail_text = $FAIL ($ATTEMPTS)
  capslock_color = $gold
  position = 0, -47
  halign = center
  valign = center
}
